import {
  addImports,
  addPlugin,
  addServerHandler,
  addServerImports,
  addServerPlugin,
  addTypeTemplate,
  createResolver,
  defineNuxtModule,
} from '@nuxt/kit'
import { defu } from 'defu'

export interface ModuleOptions {
  /**
   * Enable sending payloads to Buggregator / Ray.
   * @default true
   */
  enabled?: boolean
  /**
   * Buggregator host (reachable from Nitro — Docker IP, localhost, etc.).
   * @default '127.0.0.1'
   */
  host?: string
  /**
   * Buggregator port.
   * @default 8000
   */
  port?: number
  /**
   * Buggregator scheme.
   * @default 'http'
   */
  scheme?: 'http' | 'https'
  /**
   * Buggregator project key (Basic Auth password for user `ray`).
   * @default ''
   */
  project?: string
  /**
   * Max depth for auto-expanded sf-dump trees.
   * @default 3
   */
  maxDepth?: number
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'nuxt-buggregator',
    configKey: 'buggregator',
    compatibility: {
      nuxt: '>=4.0.0',
    },
  },
  defaults: {
    enabled: true,
    host: '127.0.0.1',
    port: 8000,
    scheme: 'http',
    project: '',
    maxDepth: 3,
  },
  setup(options, nuxt) {
    const resolver = createResolver(import.meta.url)

    // Private: full endpoint for the proxy (never sent to the browser)
    nuxt.options.runtimeConfig.buggregator = defu(nuxt.options.runtimeConfig.buggregator, {
      host: options.host,
      port: options.port,
      scheme: options.scheme,
      project: options.project,
      enabled: options.enabled,
      maxDepth: options.maxDepth,
    })

    // Public: only what the browser needs for dump + gate
    nuxt.options.runtimeConfig.public.buggregator = defu(
      nuxt.options.runtimeConfig.public.buggregator,
      {
        enabled: options.enabled,
        maxDepth: options.maxDepth,
      },
    )

    nuxt.options.build = nuxt.options.build || {}
    nuxt.options.build.transpile = nuxt.options.build.transpile || []
    nuxt.options.build.transpile.push(resolver.resolve('./runtime'))

    addServerHandler({
      route: '/api/_buggregator',
      method: 'post',
      lazy: true,
      handler: resolver.resolve('./runtime/server/api/ingest.post'),
    })

    addServerHandler({
      route: '/api/_buggregator/locks/**:name',
      method: 'get',
      lazy: true,
      handler: resolver.resolve('./runtime/server/api/locks/[...name].get'),
    })

    addPlugin({
      src: resolver.resolve('./runtime/app/plugins/buggregator.client'),
      mode: 'client',
    })

    addPlugin({
      src: resolver.resolve('./runtime/app/plugins/buggregator.server'),
      mode: 'server',
    })

    addServerPlugin(resolver.resolve('./runtime/server/plugins/buggregator'))

    addImports({
      name: 'useRay',
      from: resolver.resolve('./runtime/app/composables/useRay'),
    })

    addServerImports([
      {
        name: 'ray',
        from: resolver.resolve('./runtime/server/utils/ray'),
      },
      {
        name: 'ensureBuggregatorRay',
        from: resolver.resolve('./runtime/server/utils/ray'),
      },
    ])

    addTypeTemplate({
      filename: 'types/nuxt-buggregator.d.ts',
      getContents: () => `// Generated by nuxt-buggregator
import type { RayFn } from '${resolver.resolve('./runtime/core/ray')}'

declare module '@nuxt/schema' {
  interface RuntimeConfig {
    buggregator: {
      enabled: boolean
      host: string
      port: number
      scheme: string
      project: string
      maxDepth: number
    }
  }

  interface PublicRuntimeConfig {
    buggregator: {
      enabled: boolean
      maxDepth: number
    }
  }

  interface NuxtConfig {
    buggregator?: {
      enabled?: boolean
      host?: string
      port?: number
      scheme?: 'http' | 'https'
      project?: string
      maxDepth?: number
    }
  }

  interface NuxtOptions {
    buggregator: {
      enabled: boolean
      host: string
      port: number
      scheme: 'http' | 'https'
      project: string
      maxDepth: number
    }
  }
}

declare module '#app' {
  interface NuxtApp {
    $ray: RayFn
  }
}

declare module 'vue' {
  interface ComponentCustomProperties {
    $ray: RayFn
  }
}

export {}
`,
    })
  },
})
