name: ci

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - uses: actions/setup-node@v5
              with:
                  node-version: '24'
                  cache: npm

            - name: Install
              run: npm ci

            - name: Prepare
              run: npm run dev:prepare

            - name: Check
              run: ./node_modules/.bin/vp check

            - name: Test
              run: ./node_modules/.bin/vp test

            - name: Build
              run: npm run prepack
